image: docker:latest
stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

Build&TEST:
  stage: build
  image: node:10.15.1-slim

  variables:
    DOCKER_DRIVER: overlay2
  retry: 2

  script:
    - apt update
    - apt install -y python make g++ git build-essential
    - export NODE_OPTIONS="--max_old_space_size=4096"
    - export PATH=$PATH:$(pwd)/node_modules/.bin
    - yarn bootstrap
    - yarn build
    - yarn test
